spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongodb3

server:
  port: 8080

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
  health:
    mongo:
      enabled: true
